# daemon runs in the background
# run something like tail /var/log/Novocoind/current to see the status
# be sure to run with volumes, ie:
# docker run -v $(pwd)/novocoind:/var/lib/novocoind -v $(pwd)/wallet:/home/novocoin --rm -ti novocoin:latest
FROM ubuntu:16.04

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /

ADD https://github.com/just-containers/socklog-overlay/releases/download/v2.1.0-0/socklog-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/socklog-overlay-amd64.tar.gz -C /

COPY . /src/novocoin


# install build dependencies
# checkout the latest tag
# build and install
RUN apt-get update && \
    apt-get install -y \
      build-essential \
      python-dev \
      gcc-4.9 \
      g++-4.9 \
      git cmake \
      libboost-all-dev && \
    cd /src/novocoin && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_CXX_FLAGS="-g0 -Os -fPIC -std=gnu++11" .. && \
    make -j$(nproc) && \
    mkdir -p /usr/local/bin && \
    cp src/Novocoind /usr/local/bin/novocoind && \
    cp src/walletd /usr/local/bin/walletd && \
    cp src/simplewallet /usr/local/bin/simplewallet && \
    cp src/miner /usr/local/bin/miner && \
    cp src/connectivity_tool /usr/local/bin/connectivity_tool && \
    strip /usr/local/bin/Novocoind && \
    strip /usr/local/bin/walletd && \
    strip /usr/local/bin/simplewallet && \
    strip /usr/local/bin/miner && \
    strip /usr/local/bin/connectivity_tool && \
    cd / && \
    rm -rf /src/Novocoin && \
    apt-get remove -y build-essential python-dev gcc-4.9 g++-4.9 git cmake libboost-all-dev && \
    apt-get autoremove -y && \
    apt-get install -y  \
      libboost-system1.58.0 \
      libboost-filesystem1.58.0 \
      libboost-thread1.58.0 \
      libboost-date-time1.58.0 \
      libboost-chrono1.58.0 \
      libboost-regex1.58.0 \
      libboost-serialization1.58.0 \
      libboost-program-options1.58.0 \
      libicu55

# setup the Novocoind service
RUN useradd -r -s /usr/sbin/nologin -m -d /var/lib/Novocoind Novocoind && \
    useradd -s /bin/bash -m -d /home/Novocoin Novocoin && \
    mkdir -p /etc/services.d/Novocoind/log && \
    mkdir -p /var/log/Novocoind && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/Novocoind/run && \^F
    echo "fdmove -c 2 1" >> /etc/services.d/Novocoind/run && \
    echo "cd /var/lib/Novocoind" >> /etc/services.d/Novocoind/run && \
    echo "export HOME /var/lib/Novocoind" >> /etc/services.d/Novocoind/run && \
    echo "s6-setuidgid Novocoind /usr/local/bin/Novocoind" >> /etc/services.d/Novocoind/run && \
    chmod +x /etc/services.d/Novocoind/run && \
    chown nobody:nogroup /var/log/Novocoind && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/Novocoind/log/run && \
    echo "s6-setuidgid nobody" >> /etc/services.d/Novocoind/log/run && \
    echo "s6-log -bp -- n20 s1000000 /var/log/Novocoind" >> /etc/services.d/Novocoind/log/run && \
    chmod +x /etc/services.d/Novocoind/log/run && \
    echo "/var/lib/Novocoind true Novocoind 0644 0755" > /etc/fix-attrs.d/Novocoind-home && \
    echo "/home/Novocoin true Novocoin 0644 0755" > /etc/fix-attrs.d/Novocoin-home && \
    echo "/var/log/Novocoind true nobody 0644 0755" > /etc/fix-attrs.d/Novocoind-logs

VOLUME ["/var/lib/Novocoind", "/home/Novocoin","/var/log/Novocoind"]

ENTRYPOINT ["/init"]
CMD ["/usr/bin/execlineb", "-P", "-c", "emptyenv cd /home/Novocoin export HOME /home/Novocoin s6-setuidgid Novocoin /bin/bash"]
